// Downloadable JAR: http://merganser.weebly.com/assessment-3.html or DIRECT DOWNLOAD AT https://drive.google.com/file/d/0B_xhR6pi2K8KV0FwMDRaWk1NdWM/view?usp=sharing
package com.mygdx.game;

/**
 * Stores an agents statistics.
 */

public class Statistics {

    private int currentHP,currentMP, maxHP, maxMP;
    private int speed,strength,dexterity,intelligence;
    private int baseArmourVal,armourVal;
    private int experience, currentLevel;
    public final int maxLevel = 20;
    public final int maxExp = 100;


    @Override
    public String toString() {
        return "Statistics{" +
                "currentHP=" + currentHP +
                ", currentMP=" + currentMP +
                ", maxHP=" + maxHP +
                ", maxMP=" + maxMP +
                ", speed=" + speed +
                ", strength=" + strength +
                ", dexterity=" + dexterity +
                ", intelligence=" + intelligence +
                ", baseArmourVal=" + baseArmourVal +
                ", armourVal=" + armourVal +
                ", experience=" + experience +
                ", currentLevel=" + currentLevel +
                ", maxLevel=" + maxLevel +
                '}';
    }

    public Statistics(int maxHP, int maxMP, int speed, int strength, int dexterity, int intelligence, int baseArmourVal, int experience, int currentLevel) {
        this.maxHP = maxHP;
        this.maxMP = maxMP;
        this.currentHP = maxHP; //Current HP & MP set to max
        this.currentMP = maxMP;

        this.speed = speed; //Determines turn order
        this.strength = strength; //Determines melee damage
        this.dexterity = dexterity; //Determines ranged damage
        this.intelligence = intelligence; //Determines magic damage

        this.baseArmourVal = baseArmourVal; //influenced by armour
        this.armourVal = baseArmourVal;

        this.experience = experience; //current amount of xp
        this.currentLevel = currentLevel;

    }
    /**
     * Empty constructor required for class to be generated by deserialising json.
     */
    public  Statistics(){};
    
    //ASSESSMENT 3 changes (5)
    public int increaseXP(int xp){
        int levelIncrease = 0;
        experience+=xp;
        levelIncrease = experience / maxExp; // assumes integer division
        currentLevel += levelIncrease;
        experience = experience % maxExp; //removed a while loop
        return levelIncrease;
    }
    //END ASSESSMENT 3 changes
    
    
    //when equipment is changed, this should be called
    public void adjustArmourVal() {

    }


    public void reduceHP(int amount){
        currentHP-=amount;
        if(currentHP<0){
            currentHP=0;
        }
    }
    public void increaseHP(int amount){
        currentHP+=amount;
        if(currentHP>maxHP)
            currentHP=maxHP;
    }

    public void increaseMP(int amount){
        currentMP+=amount;
        if(currentMP>maxMP)
            currentMP=maxMP;
    }

    public void reduceMP(int amount){
        currentMP-=amount;
        if(currentMP<0)
            currentMP=0;
    }

    /////////////
    //Get Methods
    /////////////
    public int[] getAllStats(){
        int[] x = {currentHP,currentMP,maxHP, maxMP,speed,strength,dexterity,intelligence,baseArmourVal,armourVal,experience, currentLevel};
        return x;
    }

    public int getCurrentHP() {
        return currentHP;
    }

    public int getCurrentMP() {
        return currentMP;
    }

    public int getMaxHP() {
        return maxHP;
    }

    public int getMaxMP() {
        return maxMP;
    }

    public int getSpeed() {
        return speed;
    }

    public int getStrength() {
        return strength;
    }

    public int getDexterity() {
        return dexterity;
    }

    public int getIntelligence() {
        return intelligence;
    }

    public int getBaseArmourVal() {
        return baseArmourVal;
    }

    public int getArmourVal() {
        return armourVal;
    }

    public int getExperience() {
        return experience;
    }

    public int getCurrentLevel() {
        return currentLevel;
    }

    public int getMaxExp() { return maxExp; }
}
